### PR TITLE
chore(package): update devDependencies

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Had a slow Saturday night so I updated the deps

Still have the following to look at

```
Package                   Current  Wanted  Latest  Location
babel                      5.8.23  5.8.23   6.5.2  angular-formly
babel-eslint                4.1.3   4.1.3   5.0.0  angular-formly
babel-loader                5.3.2   5.3.2   6.2.4  angular-formly
eslint                      1.7.3   1.7.3   2.4.0  angular-formly
eslint-config-kentcdodds    5.0.0   5.0.0   5.1.0  angular-formly
eslint-loader               1.1.0   1.1.0   1.3.0  angular-formly
eslint-plugin-mocha         1.0.0   1.0.0   2.0.0  angular-formly
isparta                     3.1.0   3.1.0   4.0.0  angular-formly
isparta-loader              1.0.0   1.0.0   2.0.0  angular-formly
```

Last one didn't run travis...

### CODE REVIEW

**Comment by kentcdodds** [comment]
Have you tried https://www.npmjs.com/package/next-update

**Comment by kentcdodds** [comment]
Any idea why the build is busted? Looks like a shell issue? Maybe related to the quotes you removed? Maybe we should do escaped double quotes?

**Comment by BarryThePenguin** [comment]
Ah! Yeah. I think it's the glob argument in eslint, changing it to `{test|mock}` fixes the issue. Got dragged away last minute

**Comment by kentcdodds** [comment]
Thanks @BarryThePenguin!

**Pull request merged**
