### PR TITLE
Input add-ons example

### PR DESCRIPTION
**Pull request by Ledragon**
New example of how to use input add-ons on formly fields

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks!

**Comment by Ledragon** [comment]
Most welcome!

**Comment by kentcdodds** [comment]
I can't rebuild the site right now, but it should be up on the site in the
next day or so.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by Ledragon** [comment]
Sweet. Thanks for the feedback

**Pull request merged**
