### PR TITLE
refactor(toKebabCase): replace with lodash.kebabCase

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Increases test coverage, adds a dependancy. My only hesitation is that lodash.kebabCase might behave differently

### CODE REVIEW

**Comment by kentcdodds** [comment]
Neat! Almost perfect. This just needs to be added to `dependencies` rather than `devDependencies` :-)

**Comment by kentcdodds** [comment]
Also, I think there's something wrong with the build. Don't worry about it. I'll give  it a look

**Comment by kentcdodds** [comment]
Be sure to comment when you've finished that. I wont be notified when you push changes.

**Comment by BarryThePenguin** [comment]
0.07% coverage increase!

**Comment by BarryThePenguin** [comment]
The downside is:
- formly.js increases 94KB :arrow_right: 103KB
- formly.min.js increases 20KB :arrow_right: 38KB

[My local build of formly.js](https://github.com/formly-js/angular-formly/files/4090/formly.txt)

**Comment by kentcdodds** [comment]
Ah... Hmmm... You know what... I think I'd be alright with that if we could replace some of the other util methods of formly with lodash ones...

**Comment by BarryThePenguin** [comment]
- coverage 92.80% :arrow_right: 93.01%
- formly.js increases 94KB :arrow_right: 159KB
- formly.min.js increases 20KB :arrow_right: 32KB

+0.21% coverage increase for a +60% increase in file size...  :-1:

**Comment by kentcdodds** [comment]
Hmmm... Yeah, I'm going to say that it's not worth it :-( Thanks anyway!

**Pull request closed without merging**
