### PR TITLE
fix(extras) Remove explicitAsync property closes #516

### LINKED ISSUE #516: Remove explicitAsync
As part of a deprecation of an old API, I added an `explicitAsync` property to `formlyConfig.extras` [here](https://github.com/formly-js/angular-formly/blob/6aa14c699f5eca91ea776c481b183570595e85f9/src/providers/formlyConfig.js#L31) to make it so people could opt-into the new API. I forgot to remove the property when the old api was removed.

This is probably one of the most simple [`first-timers-only`](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issues I've made. So your task will be simple. Remove that one line :-) Here are some better instructions...

- [ ] Watch [this video](https://www.youtube.com/watch?v=QOchwBm9W-g&index=5&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH) to learn what you need to do to get things setup.
- [ ] Go to [this line](https://github.com/formly-js/angular-formly/blob/6aa14c699f5eca91ea776c481b183570595e85f9/src/providers/formlyConfig.js#L31) and remove it (don't worry about the dangling comma on the line above).
- [ ] Run `git add src/`
- [ ] Run `npm run commit` and follow the prompt (In the last question where it asks about referencing issues closed, put `closes #516`).
- [ ] Push your changes to your fork, create a PR, get merged, celebrate 🎉

Thanks! Welcome to the open source community!

### PR DESCRIPTION
**Pull request by julianaramburu**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Almost perfect @julianaramburu! The convention requires a `:` between the `scope` and the `subject`. And it also requires blank lines between the subject and the related issues. So yours should be:

```
fix(extras): Remove explicitAsync property

closes #516
```

If you could kindly fix this, I would appreciate it. If you need help doing that, see [this StackOverflow answer](http://stackoverflow.com/a/179147/971592). Thanks! Sorry that the script isn't working for windows right now :-(

**Comment by julianaramburu** [comment]
All right! Let me check this and I will fix that asap! Thanks for let me
help and start contributing! Even if it's just a small tiny bit D:!


*Julián Aramburu.*

2015-10-16 17:53 GMT-03:00 Kent C. Dodds <notifications@github.com>:

**Comment by julianaramburu** [comment]
I think I'm failin' hard trying to edit the commit message lol

**Comment by kentcdodds** [comment]
If you look at the instructions, you'll want to do a force push.

Another thing you could do is just close this PR, and try again :-)

**Comment by kentcdodds** [comment]
I think I've fixed the windows issues, if you start over, everything should go much smoother :-)

**Comment by julianaramburu** [comment]
Let's try then :D


*Julián Aramburu.*

2015-10-17 10:12 GMT-03:00 Kent C. Dodds <notifications@github.com>:

**Pull request closed without merging**
