### PR TITLE
Fixed #380 - hideExpression is now called on field's model change; optimized number of field model watchers (one per object

### LINKED ISSUE #380: hideExpression not called when model property specified
I am not sure if this is correct, but I think hideExpression is not called on model update when the model property in field config is specified (different from the form model).

if I use expressionProperties: hide, it works ok.

### PR DESCRIPTION
**Pull request by redhead**
I created a new pull request, I had some problem with merging and line endings, so I done it from scratch.

It adds the second test (from hidden to visible) and a optimization of model watchers (with test as well).

### CODE REVIEW

**Comment by redhead** [comment]
Ok.. got some errors :( I will fix it

**Comment by kentcdodds** [comment]
Sorry this took so long for me to get back to you. [Work's been crazy](https://twitter.com/kentcdodds/status/627190104637898752). So, I realized late that this would actually break anyone who's using the `formly-field` directly. Even though technically the `formly-field` directive is internal, I know that I'm using it and I'm sure others are as well, so I'd prefer not to break it.

Do you think you'd have time to work in just one more piece to this PR? I'd like a test that's *something like this* pseudo code to pass:

```javascript
it('should add the model watcher when it's not the direct child of a formly-form', function() {
  const someExpressionProperty = sinon.spy();
  compileAndDigest('<div formly-field class="formly-field" options="field" model="field.model"></div>');
  scope.field.model.foo = 'hello';
  scope.$digest();
  $timeout.flush();
  expect(someExpressionProperty).to.have.been.calledOnce;
});
```

That's not complete, but hopefully you get the idea. I would expect the implementation of it would simply check the parent element (probably in the link function because I'd prefer to avoid injecting `$element` into the controller) and if it's not a `formly-form`, then add the watch as it was before.

Sorry this has been such a long-lived PR. Thanks a ton for your work on it!

**Comment by redhead** [comment]
I see. Ok, that wouldn't be a problem, I guess.
Dne 1. 8. 2015 4:13 napsal uživatel "Kent C. Dodds" <notifications@github.com>:Sorry this took so long for me to get back to you. Work's been crazy. So, I realized late that this would actually break anyone who's using the formly-field directly. Even though technically the formly-field directive is internal, I know that I'm using it and I'm sure others are as well, so I'd prefer not to break it.

Do you think you'd have time to work in just one more piece to this PR? I'd like a test that's something like this pseudo code to pass:

it('should add the model watcher when it's not the direct child of a formly-form', function() {
  const someExpressionProperty = sinon.spy();
  compileAndDigest('<div formly-field class="formly-field" options="field" model="field.model"></div>');
  scope.field.model.foo = 'hello';
  scope.$digest();
  $timeout.flush();
  expect(someExpressionProperty).to.have.been.calledOnce;
});

That's not complete, but hopefully you get the idea. I would expect the implementation of it would simply check the parent element (probably in the link function because I'd prefer to avoid injecting $element into the controller) and if it's not a formly-form, then add the watch as it was before.

Sorry this has been such a long-lived PR. Thanks a ton for your work on it!

**Comment by redhead** [comment]
This passed.

**Comment by kentcdodds** [comment]
I could see an edge case where this could be nested inside a formly-form (as a field template) and that would be a problem. But that's definitely an edge case and I don't think we need to consider that. Thanks for working on this!

**Comment by kentcdodds** [comment]
I'll release this tomorrow. I try to limit my coding on Sundays. Thanks!

**Pull request merged**
