### PR TITLE
Fix npm run in Windows (issue [#305](../../issue/305))

### PR DESCRIPTION
**Pull request by benoror**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hey @benoror, thanks for the help! A few things.

First, I don't want to have all of that commit history in the repo when I merge this. Please remove all that history and just have a single commit with your changes.

Second, I tried your changes locally and it doesn't work on my mac. I definitely want to have a solution that works everywhere. I'm thinking that a good solution would be to have a single script that sets the environment variables for us and invokes the scripts. So it would be something like:

```json
"scripts": {
  "build:dist": "node scripts/run-script.js build:dist",
  "build:prod": "node scripts/run-script.js build:prod",
  "build": "node scripts/run-script.js build",
  "test": "node scripts/run-script.js test",
  "test:single": "node scripts/run-script.js test:single",
  "test:ci": "node scripts/run-script.js test:ci",
  "watch": "node scripts/run-script.js watch",
  "start": "node scripts/run-script.js start",
  "release": "node scripts/run-script.js release"
}
```

And the `scripts/run-script.js` would actually set `process.env.NODE_ENV` before invoking the script. Do you think that would work?

**Comment by benoror** [comment]
Sorry for the mess @kentcdodds , I'm still struggling to learn OSS collaboration procedures.

I'll try again as soon as I have an Unix environment available, BTW this situation **must** have been faced by many other projects, I'll investigate

**Comment by kentcdodds** [comment]
Absolutely. Thank you for being patient and working at it. Much appreciated! :+1:

**Comment by kentcdodds** [comment]
Closing this PR. I like the middleware approach you mentioned. Feel free to take a stab at a PR for it if you're feeling ambitious :-)

**Pull request closed without merging**
