### PR TITLE
Coveralls.io Integration

### LINKED ISSUE #78: Integrate coveralls.io
A suggested in #73

### PR DESCRIPTION
**Pull request by sparty02**
This provides the necessary configuration via karma to publish coverage results to coveralls.io (pending some environment config by @kentcdodds for coveralls.io authentication).  In addition, a new test coverage badge is being added to the README.  Fixes #78

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looking at the report it's actually only reporting on the index.test.js file which contains all of angular, api-check, and angular-mocks, as well as angular-formly... Do you know of any way to make the coverage plugin leverage sourcemaps or something to make sure that 1) we're only reporting coverage for angular-formly files and 2) it reports coverage for the specific files, not just the entry file?

**Comment by sparty02** [comment]
I'll take a peek at this and circle back!

**Comment by kentcdodds** [comment]
Thanks! You're awesome! :-)

-Kent C. Dodds

**Comment by kentcdodds** [comment]
I think I've figured out a way to get coverage to exclude non-library related files. I tried it out in [angular-scope-types](https://github.com/alianza-dev/angular-scope-types/blob/master/karma.conf.js) (WIP). Just need to take the time to do it in angular-formly.

**Comment by kentcdodds** [comment]
Finally done!

**Pull request closed without merging**
