### PR TITLE
feat(FormlyFormController): Exposes FormlyFormController so it can be used outside of formly-form

### PR DESCRIPTION
**Pull request by pcardune**
## What

This change simply moves FormlyFormController into a separate file and registers it with the $controller service. There is no change in functionality.

## Why

For the formly plugin I am writing, I want to reuse the logic in the FormlyFormController with a
different directive. This change makes the controller available to third party code via the
`$controller` service. See an example of the usage here: https://github.com/Shoobx/plato-form/commit/aa609b49532af036274351acc014060ca8ee5d8c#diff-61cd5ccb0f47d71f982481c6bb4a2fa6R40

## How

The diff is fairly self explanatory.

For issue #663 

Checklist:

* [x] Follows the commit message [conventions](https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md)
* [x] Is [rebased with master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github)
* [x] Is [only one (maybe two) commits](https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 57742fdd9c6fdddbe731f37a35671a01716fdfe2
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by kentcdodds** [comment]
I think this looks good. Could you [update the commit message](https://help.github.com/articles/changing-a-commit-message/) so the subject isn't so long?

I'll let someone else merge this once you've done that. Thanks!

**Comment by BarryThePenguin** [comment]
Awesome! I've been thinking of doing the same thing for a while now... If there's any tests in `formly-form.test.js` that don't have a `compileAndDigest` in them, would be good to seperate them into a different file too

**Comment by BarryThePenguin** [comment]
Maybe even just a controller test file that is empty for now?

**Comment by pcardune** [comment]
I managed to extract out the tests for the fieldTransform config option. A lot of the other tests look a bit more tricky to extract.

**Comment by kentcdodds** [comment]
LGTM! Thanks!

**Pull request merged**
