### PR TITLE
Fix for #410

### PR DESCRIPTION
**Pull request by bmacheski**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome! This is perfect. Thanks for working on it! Welcome to the wonderful world of open source :-)

**Comment by kentcdodds** [comment]
Feedback is welcome. How did it go? Were my instructions helpful? How could I have improved on this?

**Comment by kentcdodds** [comment]
Also, what's your twitter handle?

**Comment by bmacheski** [comment]
10/10 :+1:

**Comment by kentcdodds** [comment]
Hey @bmacheski, I'm writing a blogpost that references this PR, do you mind if I reference you in it? https://medium.com/@kentcdodds/78281ea47455

**Comment by kentcdodds** [comment]
Linking this to #410

**Comment by bmacheski** [comment]
Sure. I don't mind at all.

**Comment by amangupta01** [comment]
Hey @kentcdodds, I'm beginner in opensource. Can you please give me some instructions to make some meaningful changes in code.

**Comment by kentcdodds** [comment]
Hi @amangupta01 👋 
Welcome! I'm not maintaining this library anymore, however I do have [this article](http://kcd.im/what-oss) that could help you find a library that you would be interested in contributing to. I also have [a free video course](http://kcd.im/pull-request) that teaches how to contribute to a project once you've found one.

Good luck!

**Comment by amangupta01** [comment]
Thanks @kentcdodds, but I know how to contribute and creating pull requests stuff and I have tried many projects but I can't find bugs and thus still haven't changed any code a bit.

**Comment by kentcdodds** [comment]
Ah, well, if you read the article I linked, I give some tips on finding libraries that you could contribute code to :)

**Pull request merged**
