### PR TITLE
test(formly-field): should run field expressions when form is initialised

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Skipped test for #602

### CODE REVIEW

**Comment by kentcdodds** [comment]
Just to clarify, this is intended to only run the hide expression right? Other expressionProperties won't work until the field itself is compiled.

**Comment by kentcdodds** [comment]
Based on the test, I'm guessing that is the case. Thanks!

**Comment by BarryThePenguin** [comment]
This is just for hide expression yeah...

Would it be possible to run expressionProperties after the field is compiled? That's what I'm trying to figure out

**Comment by kentcdodds** [comment]
Yes, go to the link function where we're chaining the steps of the promises to compile the template and just add another step or add to an existing step

**Pull request merged**
