### PR TITLE
fix(formly-field): Added fix for nested object properties - issue num…

### PR DESCRIPTION
**Pull request by MCKRUZ**
…ber 531

Added new methods for getters and setters to use

### CODE REVIEW

**Comment by kentcdodds** [comment]
Perfect! Thanks! High five!

**Comment by MCKRUZ** [comment]
Yay!  Nice.  Quick question...when do you think there will be an official release with this improvement?  I'm having to hack my build right now to get it to work.

**Comment by kentcdodds** [comment]
Should be out now!

**Comment by MCKRUZ** [comment]
Nice!  Thanks Kent!  I enjoyed contributing!  Hopefully I can continue to do so on a regular basis.

**Comment by mickomicko5573** [comment]
Hi Kent,
Is there a way to know when formly done render?
Thanks.

**Pull request merged**
