### PR TITLE
Added ability to add custom class to ngTransclude. Fixes #398.

### LINKED ISSUE #398: custom field class
I'm working on a [uikit](http://getuikit.com) module for angular-formly, but I have 2 issues:

* The field repeat class is hard coded, I would like a way to add a custom class to the 'formly-field' directive.
* Similarly I would like a way to add a custom class to the ngTransclude that wraps the transcluded content from the page template.

This is somewhat related to #276.

### PR DESCRIPTION
**Pull request by DevanB**
Yes, there are three commits apparently in this PR. I realized that you said the wrong issue number in your instructions, so I went back to amend the commit to reference #398 correctly.

Hope I did this correctly! :)

### CODE REVIEW

**Comment by kentcdodds** [comment]
Awesome @DevanB. This is basically identical to my solution :-) Do you think you could squash this all into [a single commit](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)? I like to keep my git commit history clean. If you need help with that, let me know :-)

**Comment by DevanB** [comment]
@kentcdodds 

Okay. I definitely didn't squash (couldn't get it working). Just reseted, recommitted, and force pushed.

I *think* it is all correct now.

**Comment by kentcdodds** [comment]
Looks perfect! Welcome to the wonderful world of open source :-) 👏

**Comment by kentcdodds** [comment]
This has been released in the official `6.21.0` release. Thanks!

**Comment by kentcdodds** [comment]
Hey @DevanB, I'm writing a blogpost that references this PR, do you mind if I reference you in it? https://medium.com/@kentcdodds/78281ea47455

**Comment by DevanB** [comment]
Yeah, go for it! It was a great feeling having accomplished that :)

On Tue, Aug 4, 2015 at 9:45 AM, Kent C. Dodds <notifications@github.com>
wrote:

> Hey @DevanB <https://github.com/DevanB>, I'm writing a blogpost that
> references this PR, do you mind if I reference you in it?
> https://medium.com/@kentcdodds/78281ea47455
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/formly-js/angular-formly/pull/401#issuecomment-127637843>
> .
>



-- 
Devan Beitel

**Pull request merged**
