### PR TITLE
Make formly work on IE8

### PR DESCRIPTION
**Pull request by koenweyn**
Sadly I have to support IE8 for our project, so I spent some time to get formly to work.
I pulled it off by adding the necessary custom tags, and using a different method of locating tags.
Also added some unit tests for formly-form and for the new tag location functionality.

### CODE REVIEW

**Comment by koenweyn** [comment]
Looks like Travis CI is having issues connection to github:
```
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=Connection timed out
```

**Comment by kentcdodds** [comment]
@koenweyn, you're awesome. This is a terrific PR. One thing that could make it even better is a section about browser support in the README (and a note about the need to include polyfills). Do you think you could add this? Thank you!

**Comment by koenweyn** [comment]
I will, as soon as I find out how to add commits to a PR ;-)

**Comment by kentcdodds** [comment]
You just commit and push to your branch. It'll get added automagically :-)

**Comment by kentcdodds** [comment]
@koenweyn, GitHub has been experiencing a DDoS attack for the last day and a half (are people insane?) so I think this is why Travis has been having trouble.

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by kentcdodds** [comment]
This has been released as part of 4.2.1 (had trouble with 4.2.0) :-) Thanks!

**Pull request merged**
