### PR TITLE
Adding support for strings in `model` property, `key` in `fieldGroup` (original issue #311)

### PR DESCRIPTION
**Pull request by benoror**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks awesome! On mobile so I'll look more closely later. But one thing for sure I noticed. Could you actually do the package.json script update in a separate PR? There's an issue for it. Thanks!

**Comment by benoror** [comment]
Hi @kentcdodds !

The `local-examples/` demo works, but to be honest I'm not 100% sure my implementation is correct

**Comment by benoror** [comment]
You mean issue https://github.com/formly-js/angular-formly/issues/305?

**Comment by benoror** [comment]
Also added support for `key` property in fieldGroup, but again I'm not totally confident of my patch. I had to comment-out one failing test. I guess I'm setting the model the wrong way. 

Let me know your thoughts. Regards!

**Comment by kentcdodds** [comment]
Yeah, 305. Can you make sure it works on Mac too?

I'll have a closer look tomorrow. Thanks!

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Sorry, I decided to go about it a different direction. Thanks though. You definitely helped out!

**Comment by kentcdodds** [comment]
See [the tests](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.test.js#L838-L926) for how to use it.

**Comment by benoror** [comment]
It works like a charm, thanks @kentcdodds !

BTW, would it be much trouble to support `key` property in fieldGroup? A use-case would be to support multi-level nested forms:

Model:
```
    vm.formData = {
          "name": "John",
          "address": {
              "streetnum": "145 Elm St.",
              "place": {
				"state": "GA",
				"city": "Atlanta"
			  }
          }
    };
```

Fields:
```
    vm.formFields = [
      {
        key: 'name',
        type: 'input',
        templateOptions: {
          label: 'Name'
        }
      },
      {
        key: 'address',
        fieldGroup: [
          {
            key: 'streetnum',
            type: 'input',
            templateOptions: {
              label: 'Street Num'
            }
          },
          {
            key: 'place',
            fieldGroup: [
				{
					key: 'state',
					type: 'input',
					templateOptions: {
					  label: 'State'
					}
				},
				{
					key: 'city',
					type: 'input',
					templateOptions: {
					  label: 'City'
					}
				}
			]
          }
        ]
      }
    ];
```

**Comment by kentcdodds** [comment]
Should be able to do that with the model property...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by benoror** [comment]
Wouldn't that be akward/counterintuitive?:

```
    vm.formFields = [
      {
        key: 'name',
        // ...
      },
      {
        model: 'model.address',
        fieldGroup: [
          {
            key: 'streetnum',
            // ...
          },
          {
            model: 'model.address.place',
            fieldGroup: [
                {
                    key: 'state',
                    // ...
                },
                {
                    key: 'city',
                    // ...
                }
            ]
          }
        ]
      }
    ];
```

**Comment by benoror** [comment]
Wow [that was fast](https://github.com/formly-js/angular-formly/commit/67065e9cad7e9d05e38f32014f2688364daa9b17) @kentcdodds ! I was already working on it but was nowhere near, you saved my day!,Thanks!

**Pull request closed without merging**
