### PR TITLE
fix(): added  functionality for issue number 531

### PR DESCRIPTION
**Pull request by MCKRUZ**
swaped out obj[prop] functionality for  for deep level objects

### CODE REVIEW

**Comment by MCKRUZ** [comment]
Ok I think I got it.

**Comment by kentcdodds** [comment]
:-( your other PR had tests :-( also, your commit message needs to have a scope: `fix(formly-field) `

**Comment by MCKRUZ** [comment]
Bah!!!  I forgot to include the tests!  Le sigh….ok  I’ll try again later.

**Comment by kentcdodds** [comment]
ping?

**Pull request closed without merging**
