### PR TITLE
Thinking about moving some logic from formly-field. But I'm thinking …

### PR DESCRIPTION
**Pull request by shanaithal**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Is there a reason you created this PR?

**Comment by shanaithal** [comment]
I wanted to start contributing to Open Source..

**Comment by kentcdodds** [comment]
Awesome! Welcome! :wave:

Check out the open issues with the `up-for-grabs` label: https://github.com/formly-js/angular-formly/issues?utf8=%E2%9C%93&q=label%3Aup-for-grabs+is%3Aissue+is%3Aopen

Also, if you're a first timer to open source, then occasionally I add a `first-timers-only` label to issues. For more info on that, see [this](https://medium.com/@kentcdodds/first-timers-only-78281ea47455).

**Comment by kentcdodds** [comment]
I also recommend you follow [@yourfirstpr](https://twitter.com/yourfirstpr) on twitter. And [me too](https://twitter.com/kentcdodds) as I will often tweet when I open a new `first-timers-only` issue.

**Comment by shanaithal** [comment]
Thank you
Yes I'm a first timer....

**Pull request closed without merging**
