### PR TITLE
Unit tests and example for ng-required

### PR DESCRIPTION
**Pull request by koenweyn**
I recently was struggling to understand how to use ngModelAttrsManipluator to set a dynamic ng-required.
So I added a unit test and a new jsbin example (as requested in #156 ;-))

### CODE REVIEW

**Comment by kentcdodds** [comment]
Love it! Thanks! You've been an awesome contributor ([bridge crosser/builder](https://www.youtube.com/watch?v=dJFV8wFU23A))!

Looking at the commits, it looks like you have a few extra commits in there which are bringing your repo up to date with angular-formly. Would really appreciate this PR to be a single commit to keep the history clean. Could you resubmit a new PR that just has a single commit with the changes? Thanks again!

**Comment by koenweyn** [comment]
Sure, if only I knew how to do that ;-)
I'll try to find out...

**Comment by kentcdodds** [comment]
The quick and easy way is to just delete your fork and refork :-)

**Comment by koenweyn** [comment]
I did it the hard way: http://stackoverflow.com/questions/5256021/send-a-pull-request-on-github-for-only-latest-commit

**Pull request closed without merging**
